// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH3XOIM9FJNv6rxtAsRn1haKmW_Y_RGmg',
    appId: '1:1097750035726:web:bd3f66f902342fe485eb5f',
    messagingSenderId: '1097750035726',
    projectId: 'geridonusum-52c78',
    authDomain: 'geridonusum-52c78.firebaseapp.com',
    storageBucket: 'geridonusum-52c78.firebasestorage.app',
    measurementId: 'G-MSY3E9TW9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7-H0Dfx-t613Fa-x5kiErfy-mZZL3nVM',
    appId: '1:1097750035726:android:71c2ced8707be75885eb5f',
    messagingSenderId: '1097750035726',
    projectId: 'geridonusum-52c78',
    storageBucket: 'geridonusum-52c78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJSsTta3gOo5PVujii7ky088UMa8CRz4E',
    appId: '1:1097750035726:ios:a594d672d542f85685eb5f',
    messagingSenderId: '1097750035726',
    projectId: 'geridonusum-52c78',
    storageBucket: 'geridonusum-52c78.firebasestorage.app',
    iosBundleId: 'com.example.izamacapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJSsTta3gOo5PVujii7ky088UMa8CRz4E',
    appId: '1:1097750035726:ios:a594d672d542f85685eb5f',
    messagingSenderId: '1097750035726',
    projectId: 'geridonusum-52c78',
    storageBucket: 'geridonusum-52c78.firebasestorage.app',
    iosBundleId: 'com.example.izamacapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH3XOIM9FJNv6rxtAsRn1haKmW_Y_RGmg',
    appId: '1:1097750035726:web:e755c937cd32118285eb5f',
    messagingSenderId: '1097750035726',
    projectId: 'geridonusum-52c78',
    authDomain: 'geridonusum-52c78.firebaseapp.com',
    storageBucket: 'geridonusum-52c78.firebasestorage.app',
    measurementId: 'G-L42J2MX4RR',
  );
}
